# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Ian CR
email: iancastillorosales@gmail.com
baseurl: ""
url: "https://carian2996.github.io"
twitter_username: carian_2996
github_username:  carian2996
paginate: 5

gems: [jekyll-paginate, kramdown, jekyll-gist]
# Build settings
markdown: kramdown
